# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This (cpp) function generates a bivariate chain according to homework_10
#'
#' @param N length of the chain
#' @export
cppbivariate_chain <- function(N) {
    .Call('_StatComp21091_cppbivariate_chain', PACKAGE = 'StatComp21091', N)
}

