# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by two
#'
#' @param x A single integer.
#' @export
timesTwo <- function(x) {
    .Call('_StatComp21091_timesTwo', PACKAGE = 'StatComp21091', x)
}

#' Test
#'
#' @param N length of the chain
#' @export
cppbivariate_chain <- function(N) {
    .Call('_StatComp21091_cppbivariate_chain', PACKAGE = 'StatComp21091', N)
}

#' Multiply a number by three
#'
#' @param x A single integer.
#' @export
timesThree <- function(x) {
    .Call('_StatComp21091_timesThree', PACKAGE = 'StatComp21091', x)
}

